# 1.Numpy基础知识


## 1.1 矩阵及其定义

In [21]:
import numpy

ins_array = numpy.array([[1, 2, 3], [4, 5, 6]])

print(ins_array)
print("维数:\t", ins_array.ndim)
print("行列数:\t", ins_array.shape)
print("大小:\t", ins_array.size)

[[1 2 3]
 [4 5 6]]
维数:	 2
行列数:	 (2, 3)
大小:	 6


In [22]:
a = numpy.array([1, 2, 3], dtype=numpy.float)
print("a矩阵的数据类型：" + str(a.dtype))

a矩阵的数据类型：float64


In [23]:
# 定义一个3行4列的零矩阵
b = numpy.zeros((3, 4))      # 默认是float64
print("b矩阵的数据类型：" + str(b.dtype))

c = numpy.zeros((2, 5), dtype=numpy.int)
print(c)

b矩阵的数据类型：float64
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
# 定义一个单位矩阵
d = numpy.ones((3, 3))      # 默认是float64
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# 定义一个空矩阵
e = numpy.empty((3, 4))
print(e)

[[0.61772571 0.59486727 0.57892003 0.29061079]
 [0.23020622 0.20892927 0.4431468  0.95100527]
 [0.1663929  0.95746571 0.33401785 0.53065095]]


In [26]:
f = numpy.arange(0, 10, 2)  # 从0到10每隔2生成一个数据
# 左闭右开区间
print(f)

[0 2 4 6 8]


In [27]:
# 生成12个数，并重新排列为3行4列
g = numpy.arange(12).reshape((3, 4))
print(g)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
h = numpy.linspace(1, 10, 20).reshape(4,5)      # 从1到10分为20段
print(h)

[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


### 随机生成

随机生成(0,1)的数作为矩阵元素

`i = numpy.random.random((3,4))`

+ 第一个random是模块，第二个random是函数
+ 括号内定义shape，元组形式，不要忘了括号（外层括号是函数的，内层括号是元组的）

In [29]:
i = numpy.random.random((3,4))

print(i)

[[0.13277498 0.29571061 0.9741199  0.19671741]
 [0.95046802 0.88939578 0.86678486 0.56430966]
 [0.36057012 0.11256988 0.84930197 0.25469173]]


# 2.Numpy运算基础

In [30]:
import numpy
import math

A = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = numpy.array([
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6]
])

## 2.1 矩阵运算

Numpy 提供了基础的矩阵算法，其计算逻辑和线性代数完全一致。

矩阵的知识点
+ 矩阵的运算：加乘（法）乘（方）转方逆
+ 初等变换与初等矩阵
+ 秩及其公式

### 2.1.1 矩阵的加法

In [31]:
print("A + B = ")
print(A + B)

A + B = 
[[ 8 10 12]
 [ 5  7  9]
 [11 13 15]]


### 2.1.2 矩阵的乘法

矩阵的乘法满足：
+ 交换律：不满足
+ 消去律：
+ 零因子律

#### 2.1.2.1 矩阵乘法的运算

【注意】在Numpy中，如果定义的array用作数组，只是对应元素相乘，那么直接用“*”即可。但如果希望使用矩阵的乘法，则应当使用

```python
numpy.dot(A, B)
```

或者：

```python
A.dot(B)
```

矩阵乘法不满足交换律

In [32]:
print("A = \n", A, "\n\n", "B = \n", B, "\n")
print("A、B对应相乘（非矩阵乘法）：\n", A * B)
print("\n")

AB = numpy.dot(A, B)
print("A、B矩阵相乘（矩阵的乘法）：\n", AB)

print("\n")

BA = B.dot(A)
print("B、A矩阵相乘（矩阵的乘法）：\n", BA)

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 B = 
 [[7 8 9]
 [1 2 3]
 [4 5 6]] 

A、B对应相乘（非矩阵乘法）：
 [[ 7 16 27]
 [ 4 10 18]
 [28 40 54]]


A、B矩阵相乘（矩阵的乘法）：
 [[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


B、A矩阵相乘（矩阵的乘法）：
 [[102 126 150]
 [ 30  36  42]
 [ 66  81  96]]


#### 2.1.2.2 一行乘一列与一列乘一行

根据线性代数的相关知识：
+ 一行乘一列将得到一个数；
+ 一列乘一行将得到一个矩阵。

证明$AA^{T} = A^{T}A$，

In [33]:
a = numpy.array([[1, 2, 3]])
b = numpy.array([
    [1], 
    [2], 
    [3]
])

print("a = \n", a, "\n\n", "b = \n", b, "\n")
ab = numpy.dot(a, b)
print("行·列：a·b = \n", ab, "\n")
ba = numpy.dot(b, a)
print("列·行：b·a = \n", ba)

a = 
 [[1 2 3]] 

 b = 
 [[1]
 [2]
 [3]] 

行·列：a·b = 
 [[14]] 

列·行：b·a = 
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


### 2.1.3 矩阵的乘方
A^n 的五种计算
#### 2.1.3.1 

#### 2.1.3.2 可逆矩阵
$$			
A^{n} = P \Lambda P^{-1}
$$

### 2.1.4 矩阵的转置

矩阵转置的相关公式：
$$
A^{T} = A \\
(AB)^{T} = B^{T}A^{T}  类似：(AB)^{-1} = B^{-1}A^{-1}; (AB)^{*} = B^{*}A^{*}\\
(A+B)^{T} = B^{T} + A^{T} \\
(kA)^{T} = kA^{T}
$$
转置、可逆、？？三种运算时可交换的：
$$
(A^{T})^{-1} = (A^{-1})^{T} \\
(A^{-1})^{*} = (A^{*})^{-1} \\
(A^{*})^{T} = (A^{T})^{*}
$$

### 2.1.5 矩阵的逆运算

（可逆的前提是方阵）

#### 求可逆矩阵

1、定义法（多用于抽象矩阵）
$$
A \cdot (?) = E， 则： (?) = A^{-1}
$$

2、公式法
$$
A^{-1} = \frac{A^{*}}{|A|}
$$

3、初等矩阵法

对$(A, E)$矩阵进行初等行变换至$(E, B)$，所得到的B矩阵就是A的逆矩阵

## 2.2 初等变换与初等矩阵

左乘行变换，右乘列变换


In [34]:
E = numpy.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

E_ij = numpy.array([
    [1, 0, 0],
    [0, 0, 1],
    [0, 1, 0]
])

print("A = \n", A, "\n\n", "E_ij = \n", E_ij, "\n")

EijA = numpy.dot(E_ij, A)
print("E_ij · A = \n", EijA)
print("左乘行变换\n")

AEij = numpy.dot(A, E_ij)
print("A · E_ij  = \n", AEij)
print("右乘列变换\n")

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 E_ij = 
 [[1 0 0]
 [0 0 1]
 [0 1 0]] 

E_ij · A = 
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
左乘行变换

A · E_ij  = 
 [[1 3 2]
 [4 6 5]
 [7 9 8]]
右乘列变换



## 2.4 矩阵的秩

### 定义

最高阶非零子式的阶数

### 应用

+ $A \neq 0  \Leftrightarrow  r(A) \geq 1$
+ $A \neq 0  \Leftrightarrow  r(A) \geq 1$

## 2.2 三角函数

In [35]:
angle = numpy.array([0, 30, 45, 60, 90, 180])
print(math.pi/180)
sin_value = numpy.sin(angle * ((2*(math.pi))/360))
cos_value = numpy.cos(angle * ((2*(math.pi))/360))
print(sin_value)
print(cos_value)

0.017453292519943295
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]


## 2.3 判断大小

判断矩阵中元素是否符合给定的条件，返回布尔值。

【注意】需要注意的是，判断等于用“==”，而不是“=”

In [36]:
print(A > 3)
print(B == 4)

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [ True False False]]


## 2.4 求和与求最值

In [44]:
print("A = \n", A, "\n\n")

# 在全部矩阵中操作
print("求和：", numpy.sum(A))
print("最小：", numpy.min(A))
print("最大：", numpy.max(A))

print("\n")

# 在某一行、列中操作
print("在每一行中：")
print("求和：", numpy.sum(A, axis=1))
print("最小：", numpy.min(A, axis=1))
print("最大：", numpy.max(A, axis=1))

print("\n")

print("在每一列中：")
print("求和：", numpy.sum(A, axis=0))
print("最小：", numpy.min(A, axis=0))
print("最大：", numpy.max(A, axis=0))

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 


求和： 45
最小： 1
最大： 9


在每一行中：
求和： [ 6 15 24]
最小： [1 4 7]
最大： [3 6 9]


在每一列中：
求和： [12 15 18]
最小： [1 2 3]
最大： [7 8 9]


Visual Studio Code 提示没有安装 ipykernel，通过命令行安装在了真实环境下，由于附带安装的包较多，特此记录：
```
Installing collected packages: 
pywin32, 
ipython-genutils, 
decorator, 
traitlets, 
jupyter-core, 
tornado, 
pyzmq, 
python-dateutil, 
jupyter-client, 
wcwidth, 
prompt-toolkit, 
backcall, 
parso, 
jedi, 
pygments, 
pickleshare, 
ipython, 
ipykernel
```